PROJECT = chat
DEPS = cowboy erlbus jiffy
dep_cowboy = git https://github.com/ninenines/cowboy master
dep_erlbus = git https://github.com/cabol/erlbus master
dep_jiffy = git https://github.com/davisp/jiffy master

include erlang.mk
